# Variables para el laboratorio acad√©mico
servicios_basicos:
  - { nombre: ssh,     estado: iniciado, habilitado: true }
  - { nombre: cron,    estado: iniciado, habilitado: true }
  - { nombre: apache2, estado: detenido, habilitado: false }

procesos_a_mostrar: 10
