$ANSIBLE_VAULT;1.1;AES256
66626434663332346361323566613364366135643338636364303864336230666466393966373737
3539353133316564313139396562636461656532666130330a353630623863653061356561653863
30663639626461613837626531336436616532346530376264616531373039323065643565616330
6531636332323461370a653033623339303933383761656231646438376232623131303962396536
61616337393964336336653739653932363537363836316231306662363166336334393664663935
39643738383435663462666563613234643266656138313365366532373138333434613437623665
34353734383162643735613036656566373262306338306138636336333839626431636461323065
33313438363662626265
