# Nivel 2: Crear y eliminar usuarios b치sicos sin validaci칩n

- name: Crear usuarios de prueba
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    state: present
  loop:
    - testuser1
    - testuser2

- name: Eliminar usuario de prueba viejo
  become: true
  ansible.builtin.user:
    name: olduser
    state: absent

- name: Guardar evidencia del manejo b치sico
  become: true
  ansible.builtin.copy:
    dest: /var/log/usuarios_nivel2.txt
    content: |
      ### Evidencia Nivel 2 - Manejo b치sico ###
      Usuarios creados: testuser1, testuser2
      Usuario eliminado: olduser
